//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MW5.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MW5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加地理数据库图层 的本地化字符串。
        /// </summary>
        internal static string AddDatabaseLayer {
            get {
                return ResourceManager.GetString("AddDatabaseLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加图层 的本地化字符串。
        /// </summary>
        internal static string AddLayer {
            get {
                return ResourceManager.GetString("AddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加栅格图层 的本地化字符串。
        /// </summary>
        internal static string AddRasterLayer {
            get {
                return ResourceManager.GetString("AddRasterLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加矢量图层 的本地化字符串。
        /// </summary>
        internal static string AddVectorLayer {
            get {
                return ResourceManager.GetString("AddVectorLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加WMS图层 的本地化字符串。
        /// </summary>
        internal static string AddWmsLayer {
            get {
                return ResourceManager.GetString("AddWmsLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string AttributesTool {
            get {
                return ResourceManager.GetString("AttributesTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置Bing API秘钥 的本地化字符串。
        /// </summary>
        internal static string BingApiKey {
            get {
                return ResourceManager.GetString("BingApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所有图层 的本地化字符串。
        /// </summary>
        internal static string ClearLayers {
            get {
                return ResourceManager.GetString("ClearLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除选定 的本地化字符串。
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM使用 的本地化字符串。
        /// </summary>
        internal static string ComUsage {
            get {
                return ResourceManager.GetString("ComUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string CustomProviders {
            get {
                return ResourceManager.GetString("CustomProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap drop_down {
            get {
                object obj = ResourceManager.GetObject("drop_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找位置 的本地化字符串。
        /// </summary>
        internal static string FindLocation {
            get {
                return ResourceManager.GetString("FindLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GDAL 版本： 的本地化字符串。
        /// </summary>
        internal static string GDAL_version {
            get {
                return ResourceManager.GetString("GDAL_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位到坐标 的本地化字符串。
        /// </summary>
        internal static string GoToXY {
            get {
                return ResourceManager.GetString("GoToXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_legend {
            get {
                object obj = ResourceManager.GetObject("ico_legend", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_results {
            get {
                object obj = ResourceManager.GetObject("ico_results", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_tasks {
            get {
                object obj = ResourceManager.GetObject("ico_tasks", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_toolbox24 {
            get {
                object obj = ResourceManager.GetObject("ico_toolbox24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_tools {
            get {
                object obj = ResourceManager.GetObject("ico_tools", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_zoom_to_layer {
            get {
                object obj = ResourceManager.GetObject("ico_zoom_to_layer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_attribute_show {
            get {
                object obj = ResourceManager.GetObject("icon_attribute_show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_clear_selection {
            get {
                object obj = ResourceManager.GetObject("icon_clear_selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_crs_change {
            get {
                object obj = ResourceManager.GetObject("icon_crs_change", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_element_add {
            get {
                object obj = ResourceManager.GetObject("icon_element_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_folder {
            get {
                object obj = ResourceManager.GetObject("icon_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_identify {
            get {
                object obj = ResourceManager.GetObject("icon_identify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_label_add {
            get {
                object obj = ResourceManager.GetObject("icon_label_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_add {
            get {
                object obj = ResourceManager.GetObject("icon_layer_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_clear {
            get {
                object obj = ResourceManager.GetObject("icon_layer_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_create {
            get {
                object obj = ResourceManager.GetObject("icon_layer_create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_database_add {
            get {
                object obj = ResourceManager.GetObject("icon_layer_database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_db_add {
            get {
                object obj = ResourceManager.GetObject("icon_layer_db_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_edit {
            get {
                object obj = ResourceManager.GetObject("icon_layer_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_raster_add {
            get {
                object obj = ResourceManager.GetObject("icon_layer_raster_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_remove {
            get {
                object obj = ResourceManager.GetObject("icon_layer_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_save {
            get {
                object obj = ResourceManager.GetObject("icon_layer_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_vector_add {
            get {
                object obj = ResourceManager.GetObject("icon_layer_vector_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_vector_thematic_add {
            get {
                object obj = ResourceManager.GetObject("icon_layer_vector_thematic_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_measure_area {
            get {
                object obj = ResourceManager.GetObject("icon_measure_area", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_measure_distance {
            get {
                object obj = ResourceManager.GetObject("icon_measure_distance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_new_map {
            get {
                object obj = ResourceManager.GetObject("icon_new_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_pan {
            get {
                object obj = ResourceManager.GetObject("icon_pan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_pan1 {
            get {
                object obj = ResourceManager.GetObject("icon_pan1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_project_open {
            get {
                object obj = ResourceManager.GetObject("icon_project_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_quit {
            get {
                object obj = ResourceManager.GetObject("icon_quit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_save {
            get {
                object obj = ResourceManager.GetObject("icon_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_save_as {
            get {
                object obj = ResourceManager.GetObject("icon_save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_save1 {
            get {
                object obj = ResourceManager.GetObject("icon_save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_search {
            get {
                object obj = ResourceManager.GetObject("icon_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_select {
            get {
                object obj = ResourceManager.GetObject("icon_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_select_by_polygon {
            get {
                object obj = ResourceManager.GetObject("icon_select_by_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_settings {
            get {
                object obj = ResourceManager.GetObject("icon_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_snapshot {
            get {
                object obj = ResourceManager.GetObject("icon_snapshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_vertex {
            get {
                object obj = ResourceManager.GetObject("icon_vertex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_zoom_in {
            get {
                object obj = ResourceManager.GetObject("icon_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_zoom_max_extents {
            get {
                object obj = ResourceManager.GetObject("icon_zoom_max_extents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_zoom_out {
            get {
                object obj = ResourceManager.GetObject("icon_zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_zoom_to_layer {
            get {
                object obj = ResourceManager.GetObject("icon_zoom_to_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_zoom_to_selection {
            get {
                object obj = ResourceManager.GetObject("icon_zoom_to_selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_book24 {
            get {
                object obj = ResourceManager.GetObject("img_book24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_compass {
            get {
                object obj = ResourceManager.GetObject("img_compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_component32 {
            get {
                object obj = ResourceManager.GetObject("img_component32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_coordinates32 {
            get {
                object obj = ResourceManager.GetObject("img_coordinates32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_default24 {
            get {
                object obj = ResourceManager.GetObject("img_default24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_docs24 {
            get {
                object obj = ResourceManager.GetObject("img_docs24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_error_orange32 {
            get {
                object obj = ResourceManager.GetObject("img_error_orange32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_error_red32 {
            get {
                object obj = ResourceManager.GetObject("img_error_red32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_eye32 {
            get {
                object obj = ResourceManager.GetObject("img_eye32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_FindLocation {
            get {
                object obj = ResourceManager.GetObject("img_FindLocation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_folder_open32 {
            get {
                object obj = ResourceManager.GetObject("img_folder_open32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_geometry {
            get {
                object obj = ResourceManager.GetObject("img_geometry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_globe32 {
            get {
                object obj = ResourceManager.GetObject("img_globe32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_GoToXY32 {
            get {
                object obj = ResourceManager.GetObject("img_GoToXY32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_layers32 {
            get {
                object obj = ResourceManager.GetObject("img_layers32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_map32 {
            get {
                object obj = ResourceManager.GetObject("img_map32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_mapwindow_logo {
            get {
                object obj = ResourceManager.GetObject("img_mapwindow_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_mapwindow24 {
            get {
                object obj = ResourceManager.GetObject("img_mapwindow24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_measure_length {
            get {
                object obj = ResourceManager.GetObject("img_measure_length", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_measure32 {
            get {
                object obj = ResourceManager.GetObject("img_measure32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_open_layer32 {
            get {
                object obj = ResourceManager.GetObject("img_open_layer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_options {
            get {
                object obj = ResourceManager.GetObject("img_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_palette {
            get {
                object obj = ResourceManager.GetObject("img_palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_paypal24 {
            get {
                object obj = ResourceManager.GetObject("img_paypal24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_picture32 {
            get {
                object obj = ResourceManager.GetObject("img_picture32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_plugin32 {
            get {
                object obj = ResourceManager.GetObject("img_plugin32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_raster {
            get {
                object obj = ResourceManager.GetObject("img_raster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_scale24 {
            get {
                object obj = ResourceManager.GetObject("img_scale24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_SelectionByAttributes32 {
            get {
                object obj = ResourceManager.GetObject("img_SelectionByAttributes32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_SelectionSelectByLocation32 {
            get {
                object obj = ResourceManager.GetObject("img_SelectionSelectByLocation32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_server32 {
            get {
                object obj = ResourceManager.GetObject("img_server32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_suntoongis_logo {
            get {
                object obj = ResourceManager.GetObject("img_suntoongis_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_suntoongis_view {
            get {
                object obj = ResourceManager.GetObject("img_suntoongis_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_Swipe32 {
            get {
                object obj = ResourceManager.GetObject("img_Swipe32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_test24 {
            get {
                object obj = ResourceManager.GetObject("img_test24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_tiles32 {
            get {
                object obj = ResourceManager.GetObject("img_tiles32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_toolbox24 {
            get {
                object obj = ResourceManager.GetObject("img_toolbox24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_tools32 {
            get {
                object obj = ResourceManager.GetObject("img_tools32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_tune32 {
            get {
                object obj = ResourceManager.GetObject("img_tune32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_vector32 {
            get {
                object obj = ResourceManager.GetObject("img_vector32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_vector32_1 {
            get {
                object obj = ResourceManager.GetObject("img_vector32_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_warning64 {
            get {
                object obj = ResourceManager.GetObject("img_warning64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_widgets32 {
            get {
                object obj = ResourceManager.GetObject("img_widgets32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_wms_add24 {
            get {
                object obj = ResourceManager.GetObject("img_wms_add24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_world_grid32 {
            get {
                object obj = ResourceManager.GetObject("img_world_grid32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_zoom_next24 {
            get {
                object obj = ResourceManager.GetObject("img_zoom_next24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_zoom_prev24 {
            get {
                object obj = ResourceManager.GetObject("img_zoom_prev24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 清除选择 的本地化字符串。
        /// </summary>
        internal static string LayerClearSelection {
            get {
                return ResourceManager.GetString("LayerClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MapWindow版本： 的本地化字符串。
        /// </summary>
        internal static string map_window_version {
            get {
                return ResourceManager.GetString("map_window_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MapWinGIS版本： 的本地化字符串。
        /// </summary>
        internal static string map_winGIS_version {
            get {
                return ResourceManager.GetString("map_winGIS_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap mapwindow_logo {
            get {
                object obj = ResourceManager.GetObject("mapwindow_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 测量面积 的本地化字符串。
        /// </summary>
        internal static string MeasureArea {
            get {
                return ResourceManager.GetString("MeasureArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测距 的本地化字符串。
        /// </summary>
        internal static string MeasureDistance {
            get {
                return ResourceManager.GetString("MeasureDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建地图 的本地化字符串。
        /// </summary>
        internal static string NewMap {
            get {
                return ResourceManager.GetString("NewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开项目 的本地化字符串。
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平移 的本地化字符串。
        /// </summary>
        internal static string Pan {
            get {
                return ResourceManager.GetString("Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件配置 的本地化字符串。
        /// </summary>
        internal static string PluginsConfigure {
            get {
                return ResourceManager.GetString("PluginsConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap red_fill {
            get {
                object obj = ResourceManager.GetObject("red_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap red_no_fill {
            get {
                object obj = ResourceManager.GetObject("red_no_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 删除图层 的本地化字符串。
        /// </summary>
        internal static string RemoveLayer {
            get {
                return ResourceManager.GetString("RemoveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存项目 的本地化字符串。
        /// </summary>
        internal static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        internal static string SaveProjectAs {
            get {
                return ResourceManager.GetString("SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多边形工具 的本地化字符串。
        /// </summary>
        internal static string SelectByPolygon {
            get {
                return ResourceManager.GetString("SelectByPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矩形工具 的本地化字符串。
        /// </summary>
        internal static string SelectByRectangle {
            get {
                return ResourceManager.GetString("SelectByRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string SelectDropDown {
            get {
                return ResourceManager.GetString("SelectDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按属性选择要素 的本地化字符串。
        /// </summary>
        internal static string SelectionByAttribute {
            get {
                return ResourceManager.GetString("SelectionByAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按位置关系选择要素 的本地化字符串。
        /// </summary>
        internal static string SelectionSelectByLocation {
            get {
                return ResourceManager.GetString("SelectionSelectByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图投影 的本地化字符串。
        /// </summary>
        internal static string SetProjection {
            get {
                return ResourceManager.GetString("SetProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置比例尺 的本地化字符串。
        /// </summary>
        internal static string SetScale {
            get {
                return ResourceManager.GetString("SetScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示坐标 的本地化字符串。
        /// </summary>
        internal static string ShowCoordinates {
            get {
                return ResourceManager.GetString("ShowCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示重画时间 的本地化字符串。
        /// </summary>
        internal static string ShowRedrawTime {
            get {
                return ResourceManager.GetString("ShowRedrawTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示存储库 的本地化字符串。
        /// </summary>
        internal static string ShowRepository {
            get {
                return ResourceManager.GetString("ShowRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示比例尺 的本地化字符串。
        /// </summary>
        internal static string ShowScalebar {
            get {
                return ResourceManager.GetString("ShowScalebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示工具箱 的本地化字符串。
        /// </summary>
        internal static string ShowToolbox {
            get {
                return ResourceManager.GetString("ShowToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示缩放栏 的本地化字符串。
        /// </summary>
        internal static string ShowZoombar {
            get {
                return ResourceManager.GetString("ShowZoombar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap small_down_arrow {
            get {
                object obj = ResourceManager.GetObject("small_down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 驱动支持 的本地化字符串。
        /// </summary>
        internal static string SupportedDrivers {
            get {
                return ResourceManager.GetString("SupportedDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影像卷帘 的本地化字符串。
        /// </summary>
        internal static string Swipe {
            get {
                return ResourceManager.GetString("Swipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一键透明 的本地化字符串。
        /// </summary>
        internal static string SwitchFill {
            get {
                return ResourceManager.GetString("SwitchFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瓦片配置 的本地化字符串。
        /// </summary>
        internal static string TilesConfigure {
            get {
                return ResourceManager.GetString("TilesConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具栏 的本地化字符串。
        /// </summary>
        internal static string Toolbars {
            get {
                return ResourceManager.GetString("Toolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口 的本地化字符串。
        /// </summary>
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap WMS图层 {
            get {
                object obj = ResourceManager.GetObject("WMS图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到最大 的本地化字符串。
        /// </summary>
        internal static string ZoomMax {
            get {
                return ResourceManager.GetString("ZoomMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转至下一视图 的本地化字符串。
        /// </summary>
        internal static string ZoomNext {
            get {
                return ResourceManager.GetString("ZoomNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回上一视图 的本地化字符串。
        /// </summary>
        internal static string ZoomPrev {
            get {
                return ResourceManager.GetString("ZoomPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到基础层 的本地化字符串。
        /// </summary>
        internal static string ZoomToBaseLayer {
            get {
                return ResourceManager.GetString("ZoomToBaseLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到当前 的本地化字符串。
        /// </summary>
        internal static string ZoomToLayer {
            get {
                return ResourceManager.GetString("ZoomToLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到选定 的本地化字符串。
        /// </summary>
        internal static string ZoomToSelected {
            get {
                return ResourceManager.GetString("ZoomToSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 保存编辑 {
            get {
                object obj = ResourceManager.GetObject("保存编辑", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 全不选 {
            get {
                object obj = ResourceManager.GetObject("全不选", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 全图 {
            get {
                object obj = ResourceManager.GetObject("全图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 关于 {
            get {
                object obj = ResourceManager.GetObject("关于", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 分类渲染 {
            get {
                object obj = ResourceManager.GetObject("分类渲染", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 删格图层 {
            get {
                object obj = ResourceManager.GetObject("删格图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 删格格式转换 {
            get {
                object obj = ResourceManager.GetObject("删格格式转换", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 删格转多边形 {
            get {
                object obj = ResourceManager.GetObject("删格转多边形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 删除 {
            get {
                object obj = ResourceManager.GetObject("删除", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 删除当前图层 {
            get {
                object obj = ResourceManager.GetObject("删除当前图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 删除要素 {
            get {
                object obj = ResourceManager.GetObject("删除要素", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 前视图 {
            get {
                object obj = ResourceManager.GetObject("前视图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 剪切 {
            get {
                object obj = ResourceManager.GetObject("剪切", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 区域打印 {
            get {
                object obj = ResourceManager.GetObject("区域打印", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 卷帘 {
            get {
                object obj = ResourceManager.GetObject("卷帘", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 合并 {
            get {
                object obj = ResourceManager.GetObject("合并", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 后视图 {
            get {
                object obj = ResourceManager.GetObject("后视图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 地图投影 {
            get {
                object obj = ResourceManager.GetObject("地图投影", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 地理数据库 {
            get {
                object obj = ResourceManager.GetObject("地理数据库", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 复制 {
            get {
                object obj = ResourceManager.GetObject("复制", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 多边形分割 {
            get {
                object obj = ResourceManager.GetObject("多边形分割", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 多边形选择 {
            get {
                object obj = ResourceManager.GetObject("多边形选择", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 定位 {
            get {
                object obj = ResourceManager.GetObject("定位", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 导航 {
            get {
                object obj = ResourceManager.GetObject("导航", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 小班排号 {
            get {
                object obj = ResourceManager.GetObject("小班排号", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 小班照片 {
            get {
                object obj = ResourceManager.GetObject("小班照片", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 属性复制 {
            get {
                object obj = ResourceManager.GetObject("属性复制", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 属性提取 {
            get {
                object obj = ResourceManager.GetObject("属性提取", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 属性粘贴 {
            get {
                object obj = ResourceManager.GetObject("属性粘贴", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon 工具箱 {
            get {
                object obj = ResourceManager.GetObject("工具箱", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 底图 {
            get {
                object obj = ResourceManager.GetObject("底图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 开始编辑 {
            get {
                object obj = ResourceManager.GetObject("开始编辑", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 当前层 {
            get {
                object obj = ResourceManager.GetObject("当前层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 影像配准 {
            get {
                object obj = ResourceManager.GetObject("影像配准", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 所有层 {
            get {
                object obj = ResourceManager.GetObject("所有层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 手册 {
            get {
                object obj = ResourceManager.GetObject("手册", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 打印 {
            get {
                object obj = ResourceManager.GetObject("打印", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 打印机 {
            get {
                object obj = ResourceManager.GetObject("打印机", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 拆分 {
            get {
                object obj = ResourceManager.GetObject("拆分", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 拓扑检查 {
            get {
                object obj = ResourceManager.GetObject("拓扑检查", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 按属性合并 {
            get {
                object obj = ResourceManager.GetObject("按属性合并", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 按属性统计 {
            get {
                object obj = ResourceManager.GetObject("按属性统计", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 捕捉到间断点 {
            get {
                object obj = ResourceManager.GetObject("捕捉到间断点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 捕捉到顶点 {
            get {
                object obj = ResourceManager.GetObject("捕捉到顶点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 捕捉当前图层 {
            get {
                object obj = ResourceManager.GetObject("捕捉当前图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 捕捉所有图层 {
            get {
                object obj = ResourceManager.GetObject("捕捉所有图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 撤销 {
            get {
                object obj = ResourceManager.GetObject("撤销", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 放大 {
            get {
                object obj = ResourceManager.GetObject("放大", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 数据字典 {
            get {
                object obj = ResourceManager.GetObject("数据字典", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 新建图层 {
            get {
                object obj = ResourceManager.GetObject("新建图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 新建要素 {
            get {
                object obj = ResourceManager.GetObject("新建要素", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 旋转 {
            get {
                object obj = ResourceManager.GetObject("旋转", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon 智能识别 {
            get {
                object obj = ResourceManager.GetObject("智能识别", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 条件选择 {
            get {
                object obj = ResourceManager.GetObject("条件选择", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 栅格数据重投影 {
            get {
                object obj = ResourceManager.GetObject("栅格数据重投影", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 标注设置 {
            get {
                object obj = ResourceManager.GetObject("标注设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 标签移动 {
            get {
                object obj = ResourceManager.GetObject("标签移动", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 标签移动标签 {
            get {
                object obj = ResourceManager.GetObject("标签移动标签", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 欢迎 {
            get {
                object obj = ResourceManager.GetObject("欢迎", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 比例尺 {
            get {
                object obj = ResourceManager.GetObject("比例尺", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 测量距离 {
            get {
                object obj = ResourceManager.GetObject("测量距离", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 测量面积 {
            get {
                object obj = ResourceManager.GetObject("测量面积", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 添加图层 {
            get {
                object obj = ResourceManager.GetObject("添加图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 添加数据 {
            get {
                object obj = ResourceManager.GetObject("添加数据", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 添加数据1 {
            get {
                object obj = ResourceManager.GetObject("添加数据1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 清除所有图层 {
            get {
                object obj = ResourceManager.GetObject("清除所有图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 渲染全部 {
            get {
                object obj = ResourceManager.GetObject("渲染全部", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 照片设置 {
            get {
                object obj = ResourceManager.GetObject("照片设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 矢量图层 {
            get {
                object obj = ResourceManager.GetObject("矢量图层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 矢量数据重投影 {
            get {
                object obj = ResourceManager.GetObject("矢量数据重投影", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 矢量格式转换 {
            get {
                object obj = ResourceManager.GetObject("矢量格式转换", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 矩形选择 {
            get {
                object obj = ResourceManager.GetObject("矩形选择", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 移动 {
            get {
                object obj = ResourceManager.GetObject("移动", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 移动视图 {
            get {
                object obj = ResourceManager.GetObject("移动视图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 移动设备 {
            get {
                object obj = ResourceManager.GetObject("移动设备", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 空间选择 {
            get {
                object obj = ResourceManager.GetObject("空间选择", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 符号旋转 {
            get {
                object obj = ResourceManager.GetObject("符号旋转", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 粘贴 {
            get {
                object obj = ResourceManager.GetObject("粘贴", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 线分割 {
            get {
                object obj = ResourceManager.GetObject("线分割", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 线构面 {
            get {
                object obj = ResourceManager.GetObject("线构面", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 统计表 {
            get {
                object obj = ResourceManager.GetObject("统计表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 缩小 {
            get {
                object obj = ResourceManager.GetObject("缩小", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 缩放到已选 {
            get {
                object obj = ResourceManager.GetObject("缩放到已选", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 缩放已选 {
            get {
                object obj = ResourceManager.GetObject("缩放已选", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon 缩略图 {
            get {
                object obj = ResourceManager.GetObject("缩略图", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 要素信息 {
            get {
                object obj = ResourceManager.GetObject("要素信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 角度测量 {
            get {
                object obj = ResourceManager.GetObject("角度测量", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 距离测量 {
            get {
                object obj = ResourceManager.GetObject("距离测量", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 选择 {
            get {
                object obj = ResourceManager.GetObject("选择", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 重做 {
            get {
                object obj = ResourceManager.GetObject("重做", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 间断点 {
            get {
                object obj = ResourceManager.GetObject("间断点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 面积测量 {
            get {
                object obj = ResourceManager.GetObject("面积测量", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 面融合 {
            get {
                object obj = ResourceManager.GetObject("面融合", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 面转线 {
            get {
                object obj = ResourceManager.GetObject("面转线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 面透明 {
            get {
                object obj = ResourceManager.GetObject("面透明", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 顶点 {
            get {
                object obj = ResourceManager.GetObject("顶点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 顶点编辑 {
            get {
                object obj = ResourceManager.GetObject("顶点编辑", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
