//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MW5.Plugins.ShapeEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MW5.Plugins.ShapeEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 按多边形裁剪 的本地化字符串。
        /// </summary>
        internal static string ClipByPolygon {
            get {
                return ResourceManager.GetString("ClipByPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制属性 的本地化字符串。
        /// </summary>
        internal static string CopyAttributes {
            get {
                return ResourceManager.GetString("CopyAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建层 的本地化字符串。
        /// </summary>
        internal static string CreateLayer {
            get {
                return ResourceManager.GetString("CreateLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所选 的本地化字符串。
        /// </summary>
        internal static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按多边形擦除 的本地化字符串。
        /// </summary>
        internal static string EraseByPolygon {
            get {
                return ResourceManager.GetString("EraseByPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加几何图形 的本地化字符串。
        /// </summary>
        internal static string GeometryCreate {
            get {
                return ResourceManager.GetString("GeometryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原长 的本地化字符串。
        /// </summary>
        internal static string HistoryLength {
            get {
                return ResourceManager.GetString("HistoryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_edit_copy {
            get {
                object obj = ResourceManager.GetObject("icon_edit_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_edit_copy_Attr {
            get {
                object obj = ResourceManager.GetObject("icon_edit_copy_Attr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_edit_cut {
            get {
                object obj = ResourceManager.GetObject("icon_edit_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_edit_paste {
            get {
                object obj = ResourceManager.GetObject("icon_edit_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_edit_redo {
            get {
                object obj = ResourceManager.GetObject("icon_edit_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_edit_undo {
            get {
                object obj = ResourceManager.GetObject("icon_edit_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_geometry_attributes {
            get {
                object obj = ResourceManager.GetObject("icon_geometry_attributes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_geometry_create {
            get {
                object obj = ResourceManager.GetObject("icon_geometry_create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_geometry_erase_by_polygon {
            get {
                object obj = ResourceManager.GetObject("icon_geometry_erase_by_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_geometry_merge {
            get {
                object obj = ResourceManager.GetObject("icon_geometry_merge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_geometry_move {
            get {
                object obj = ResourceManager.GetObject("icon_geometry_move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_geometry_rotate {
            get {
                object obj = ResourceManager.GetObject("icon_geometry_rotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_geometry_split {
            get {
                object obj = ResourceManager.GetObject("icon_geometry_split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_geometry_split_by_polyline {
            get {
                object obj = ResourceManager.GetObject("icon_geometry_split_by_polyline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_invert_line {
            get {
                object obj = ResourceManager.GetObject("icon_invert_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_create {
            get {
                object obj = ResourceManager.GetObject("icon_layer_create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_edit {
            get {
                object obj = ResourceManager.GetObject("icon_layer_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_layer_save {
            get {
                object obj = ResourceManager.GetObject("icon_layer_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_vertex_editor {
            get {
                object obj = ResourceManager.GetObject("icon_vertex_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_delete_selected {
            get {
                object obj = ResourceManager.GetObject("img_delete_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_shape_editor32 {
            get {
                object obj = ResourceManager.GetObject("img_shape_editor32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_snap_active_layer {
            get {
                object obj = ResourceManager.GetObject("img_snap_active_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_snap_all_layers {
            get {
                object obj = ResourceManager.GetObject("img_snap_all_layers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_snap_to_segments {
            get {
                object obj = ResourceManager.GetObject("img_snap_to_segments", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_snap_to_vertices {
            get {
                object obj = ResourceManager.GetObject("img_snap_to_vertices", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 编辑层 的本地化字符串。
        /// </summary>
        internal static string LayerEdit {
            get {
                return ResourceManager.GetString("LayerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存层 的本地化字符串。
        /// </summary>
        internal static string LayerSave {
            get {
                return ResourceManager.GetString("LayerSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string MainMenuEditKey {
            get {
                return ResourceManager.GetString("MainMenuEditKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并形状 的本地化字符串。
        /// </summary>
        internal static string MergeShapes {
            get {
                return ResourceManager.GetString("MergeShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动形状 的本地化字符串。
        /// </summary>
        internal static string MoveShapes {
            get {
                return ResourceManager.GetString("MoveShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴属性 的本地化字符串。
        /// </summary>
        internal static string PasteAttributes {
            get {
                return ResourceManager.GetString("PasteAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多边形叠加 的本地化字符串。
        /// </summary>
        internal static string PolygonOverlayDropDown {
            get {
                return ResourceManager.GetString("PolygonOverlayDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除形状 的本地化字符串。
        /// </summary>
        internal static string RemoveShapes {
            get {
                return ResourceManager.GetString("RemoveShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转形状 的本地化字符串。
        /// </summary>
        internal static string RotateShapes {
            get {
                return ResourceManager.GetString("RotateShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存修改 的本地化字符串。
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 形状编辑器 的本地化字符串。
        /// </summary>
        internal static string ShapeEditorToolbar {
            get {
                return ResourceManager.GetString("ShapeEditorToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕捉当前图层 的本地化字符串。
        /// </summary>
        internal static string SnaptoActiveLayer {
            get {
                return ResourceManager.GetString("SnaptoActiveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕捉所有图层 的本地化字符串。
        /// </summary>
        internal static string SnaptoAllLayers {
            get {
                return ResourceManager.GetString("SnaptoAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕捉间断点 的本地化字符串。
        /// </summary>
        internal static string SnaptoSegments {
            get {
                return ResourceManager.GetString("SnaptoSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕捉顶点 的本地化字符串。
        /// </summary>
        internal static string SnapToVertices {
            get {
                return ResourceManager.GetString("SnapToVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按多边形拆分 的本地化字符串。
        /// </summary>
        internal static string SplitByPolygon {
            get {
                return ResourceManager.GetString("SplitByPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按段线拆分 的本地化字符串。
        /// </summary>
        internal static string SplitByPolyline {
            get {
                return ResourceManager.GetString("SplitByPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分形状 的本地化字符串。
        /// </summary>
        internal static string SplitShapes {
            get {
                return ResourceManager.GetString("SplitShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶点编辑器 的本地化字符串。
        /// </summary>
        internal static string VertexEditor {
            get {
                return ResourceManager.GetString("VertexEditor", resourceCulture);
            }
        }
    }
}
