//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MW5.Plugins.Printing.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MW5.Plugins.Printing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加图片 的本地化字符串。
        /// </summary>
        internal static string AddBitmap {
            get {
                return ResourceManager.GetString("AddBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文本 的本地化字符串。
        /// </summary>
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加图例 的本地化字符串。
        /// </summary>
        internal static string AddLegend {
            get {
                return ResourceManager.GetString("AddLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加地图 的本地化字符串。
        /// </summary>
        internal static string AddMap {
            get {
                return ResourceManager.GetString("AddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加指北针 的本地化字符串。
        /// </summary>
        internal static string AddNorthArrow {
            get {
                return ResourceManager.GetString("AddNorthArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加矩形 的本地化字符串。
        /// </summary>
        internal static string AddRectangle {
            get {
                return ResourceManager.GetString("AddRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加比例尺 的本地化字符串。
        /// </summary>
        internal static string AddScaleBar {
            get {
                return ResourceManager.GetString("AddScaleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加表 的本地化字符串。
        /// </summary>
        internal static string AddTable {
            get {
                return ResourceManager.GetString("AddTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整布局 的本地化字符串。
        /// </summary>
        internal static string AdjustPages {
            get {
                return ResourceManager.GetString("AdjustPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap anim_loading {
            get {
                object obj = ResourceManager.GetObject("anim_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换位图 的本地化字符串。
        /// </summary>
        internal static string ConvertToBitmap {
            get {
                return ResourceManager.GetString("ConvertToBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除元素 的本地化字符串。
        /// </summary>
        internal static string DeleteElement {
            get {
                return ResourceManager.GetString("DeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到位图 的本地化字符串。
        /// </summary>
        internal static string ExportToBitmap {
            get {
                return ResourceManager.GetString("ExportToBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到PDF 的本地化字符串。
        /// </summary>
        internal static string ExportToPdf {
            get {
                return ResourceManager.GetString("ExportToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_legend24 {
            get {
                object obj = ResourceManager.GetObject("ico_legend24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_pan16 {
            get {
                object obj = ResourceManager.GetObject("ico_pan16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ico_properties24 {
            get {
                object obj = ResourceManager.GetObject("ico_properties24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_align_bottom24 {
            get {
                object obj = ResourceManager.GetObject("img_align_bottom24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_align_center24 {
            get {
                object obj = ResourceManager.GetObject("img_align_center24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_align_left24 {
            get {
                object obj = ResourceManager.GetObject("img_align_left24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_align_right24 {
            get {
                object obj = ResourceManager.GetObject("img_align_right24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_align_top24 {
            get {
                object obj = ResourceManager.GetObject("img_align_top24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_align_vertical24 {
            get {
                object obj = ResourceManager.GetObject("img_align_vertical24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_close24 {
            get {
                object obj = ResourceManager.GetObject("img_close24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_compass24 {
            get {
                object obj = ResourceManager.GetObject("img_compass24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_create24 {
            get {
                object obj = ResourceManager.GetObject("img_create24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_down24 {
            get {
                object obj = ResourceManager.GetObject("img_down24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_export_pdf24 {
            get {
                object obj = ResourceManager.GetObject("img_export_pdf24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_export24 {
            get {
                object obj = ResourceManager.GetObject("img_export24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_fit_height24 {
            get {
                object obj = ResourceManager.GetObject("img_fit_height24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_fit_width24 {
            get {
                object obj = ResourceManager.GetObject("img_fit_width24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_fit24 {
            get {
                object obj = ResourceManager.GetObject("img_fit24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_group24 {
            get {
                object obj = ResourceManager.GetObject("img_group24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_insert_compass24 {
            get {
                object obj = ResourceManager.GetObject("img_insert_compass24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_insert_legend24 {
            get {
                object obj = ResourceManager.GetObject("img_insert_legend24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_insert_map24 {
            get {
                object obj = ResourceManager.GetObject("img_insert_map24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_insert_picture24 {
            get {
                object obj = ResourceManager.GetObject("img_insert_picture24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_insert_table24 {
            get {
                object obj = ResourceManager.GetObject("img_insert_table24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_insert_text24 {
            get {
                object obj = ResourceManager.GetObject("img_insert_text24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_landscape32 {
            get {
                object obj = ResourceManager.GetObject("img_landscape32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_map_zoom_in24 {
            get {
                object obj = ResourceManager.GetObject("img_map_zoom_in24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_map_zoom_max24 {
            get {
                object obj = ResourceManager.GetObject("img_map_zoom_max24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_map_zoom_out24 {
            get {
                object obj = ResourceManager.GetObject("img_map_zoom_out24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_open24 {
            get {
                object obj = ResourceManager.GetObject("img_open24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_page_number24 {
            get {
                object obj = ResourceManager.GetObject("img_page_number24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_page_setup24 {
            get {
                object obj = ResourceManager.GetObject("img_page_setup24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_pan24 {
            get {
                object obj = ResourceManager.GetObject("img_pan24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_portrait32 {
            get {
                object obj = ResourceManager.GetObject("img_portrait32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_printer24 {
            get {
                object obj = ResourceManager.GetObject("img_printer24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_printer32 {
            get {
                object obj = ResourceManager.GetObject("img_printer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_raster {
            get {
                object obj = ResourceManager.GetObject("img_raster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_rectangle24 {
            get {
                object obj = ResourceManager.GetObject("img_rectangle24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_refresh24 {
            get {
                object obj = ResourceManager.GetObject("img_refresh24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_remove24 {
            get {
                object obj = ResourceManager.GetObject("img_remove24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_save_as24 {
            get {
                object obj = ResourceManager.GetObject("img_save_as24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_save24 {
            get {
                object obj = ResourceManager.GetObject("img_save24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_scalebar24 {
            get {
                object obj = ResourceManager.GetObject("img_scalebar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_select_print_area24 {
            get {
                object obj = ResourceManager.GetObject("img_select_print_area24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_up24 {
            get {
                object obj = ResourceManager.GetObject("img_up24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_zoom_in24 {
            get {
                object obj = ResourceManager.GetObject("img_zoom_in24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_zoom_layer24 {
            get {
                object obj = ResourceManager.GetObject("img_zoom_layer24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_zoom_max24 {
            get {
                object obj = ResourceManager.GetObject("img_zoom_max24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_zoom_original24 {
            get {
                object obj = ResourceManager.GetObject("img_zoom_original24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_zoom_out24 {
            get {
                object obj = ResourceManager.GetObject("img_zoom_out24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img_zoom_region24 {
            get {
                object obj = ResourceManager.GetObject("img_zoom_region24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string InsertToolbar {
            get {
                return ResourceManager.GetString("InsertToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        internal static string InvertSelection {
            get {
                return ResourceManager.GetString("InvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载布局 的本地化字符串。
        /// </summary>
        internal static string LoadLayout {
            get {
                return ResourceManager.GetString("LoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string MainToolbar {
            get {
                return ResourceManager.GetString("MainToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平移地图 的本地化字符串。
        /// </summary>
        internal static string MapPan {
            get {
                return ResourceManager.GetString("MapPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string MapToolbar {
            get {
                return ResourceManager.GetString("MapToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大地图 的本地化字符串。
        /// </summary>
        internal static string MapZoomIn {
            get {
                return ResourceManager.GetString("MapZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小地图 的本地化字符串。
        /// </summary>
        internal static string MapZoomOut {
            get {
                return ResourceManager.GetString("MapZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新布局 的本地化字符串。
        /// </summary>
        internal static string NewLayout {
            get {
                return ResourceManager.GetString("NewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面设置 的本地化字符串。
        /// </summary>
        internal static string PageSetup {
            get {
                return ResourceManager.GetString("PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印设置... 的本地化字符串。
        /// </summary>
        internal static string PrinterSetup {
            get {
                return ResourceManager.GetString("PrinterSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复面板 的本地化字符串。
        /// </summary>
        internal static string RestorePanels {
            get {
                return ResourceManager.GetString("RestorePanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原工具栏 的本地化字符串。
        /// </summary>
        internal static string RestoreToolbars {
            get {
                return ResourceManager.GetString("RestoreToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存布局 的本地化字符串。
        /// </summary>
        internal static string SaveLayout {
            get {
                return ResourceManager.GetString("SaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        internal static string SaveLayoutAs {
            get {
                return ResourceManager.GetString("SaveLayoutAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消全选 的本地化字符串。
        /// </summary>
        internal static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择打印区域 的本地化字符串。
        /// </summary>
        internal static string SelectPrintArea {
            get {
                return ResourceManager.GetString("SelectPrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示边距 的本地化字符串。
        /// </summary>
        internal static string ShowMargins {
            get {
                return ResourceManager.GetString("ShowMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示页码 的本地化字符串。
        /// </summary>
        internal static string ShowPageNumbers {
            get {
                return ResourceManager.GetString("ShowPageNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示比例尺 的本地化字符串。
        /// </summary>
        internal static string ShowRulers {
            get {
                return ResourceManager.GetString("ShowRulers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ZoomCombo {
            get {
                return ResourceManager.GetString("ZoomCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ZoomComboLabel {
            get {
                return ResourceManager.GetString("ZoomComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放至整个页面 的本地化字符串。
        /// </summary>
        internal static string ZoomFitScreen {
            get {
                return ResourceManager.GetString("ZoomFitScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放至100% 的本地化字符串。
        /// </summary>
        internal static string ZoomOriginal {
            get {
                return ResourceManager.GetString("ZoomOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到最大范围 的本地化字符串。
        /// </summary>
        internal static string ZoomToMaximum {
            get {
                return ResourceManager.GetString("ZoomToMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ZoomToolbar {
            get {
                return ResourceManager.GetString("ZoomToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放到原始范围 的本地化字符串。
        /// </summary>
        internal static string ZoomToOriginalExtents {
            get {
                return ResourceManager.GetString("ZoomToOriginalExtents", resourceCulture);
            }
        }
    }
}
